### PR TITLE
Fix: Flow operator functions should not be invoked within composition

### LINKED ISSUE #31: Implement ViewStateProvider
## Description
Implement ViewStateProvider to fix: Flow operator functions should not be invoked within composition error

### PR DESCRIPTION
**Pull request by semanticer**
## Summary
As mentioned in #25, flows shouldn't be manipulated inside Composables. 

## Relationships

Closes #31

## Technical considerations
We already use this solution internally, we should consider extracting this to the library in the future.  

## Tests
None

## Review pointers
See if the sample app still works. The code is pretty much the same as what we do internally so it's been reviewed already.

### CODE REVIEW

File: todo-sample/src/main/java/com/toggl/komposable/sample/todo/TodoScaffold.kt [hunk 1]
```diff
@@ -25,20 +25,17 @@ import com.toggl.komposable.sample.todo.data.Identity
...
-        .map { it.backStack }
-        .collectAsStateWhenStarted(initial = listOf(AppDestination.List))
-
+    val viewState by appStore.collectViewStateWhenStarted()
+    val backStack = viewState.backStack
     val activity = LocalContext.current as AppCompatActivity
 
     activity.handleBackPressesEmitting {
-        if (backStack.size < 2) activity.finish()
+        if (viewState.backStack.size < 2) activity.finish()
```
Comment (thuutin) [inline todo-sample/src/main/java/com/toggl/komposable/sample/todo/TodoScaffold.kt:38]:
```suggestion
        if (backStack.size < 2) activity.finish()
```

**Review by thuutin — APPROVED** [review]
LGTM. I just have a tiny comment.
